import XCTest
import PostgresNIO
import NIOSSL
@testable import pgBrain

final class A_CrossDBCopyTests: XCTestCase {
    private func col(_ name: String, _ type: String = "integer") -> ColumnNode {
        ColumnNode(name: name, typeName: type, nullable: true, ordinal: 0)
    }
    private func map(_ name: String, _ type: String = "integer") -> CrossDBCopy.Mapping {
        CrossDBCopy.Mapping(sourceColumn: col(name, type), targetColumnName: name)
    }
    private func info(_ type: String, typtype: String = "b", base: String? = nil, array: Bool = false) -> CrossDBCopy.SourceColumnInfo {
        .init(targetName: "c", type: type, typtype: typtype, domainBase: base, isArray: array,
              identityOrSerial: false, notNull: false)
    }

    // MARK: pure

    func testTypeMappingFallbacks() async throws {
        let known: Set<String> = ["integer", "text", "numeric(10,2)", "citext"]
        let exists: (String) async throws -> Bool = { known.contains($0) }

        let keep = try await CrossDBCopy.chooseTargetType(for: info("citext"), exists: exists)
        XCTAssertEqual(keep.type, "citext"); XCTAssertNil(keep.warning)

        let domain = try await CrossDBCopy.chooseTargetType(for: info("app.money2", typtype: "d", base: "numeric(10,2)"), exists: exists)
        XCTAssertEqual(domain.type, "numeric(10,2)"); XCTAssertNotNil(domain.warning)

        let enumType = try await CrossDBCopy.chooseTargetType(for: info("app.mood", typtype: "e"), exists: exists)
        XCTAssertEqual(enumType.type, "text"); XCTAssertTrue(enumType.warning?.contains("enum") ?? false)

        let enumArray = try await CrossDBCopy.chooseTargetType(for: info("app.mood[]", typtype: "b", array: true), exists: exists)
        XCTAssertEqual(enumArray.type, "text[]")
    }

    func testCreateTableSQLWithIdentityNotNullAndPK() {
        let sql = CrossDBCopy.createTableSQL(schema: "s", table: "t", columns: [
            .init(name: "id", type: "bigint", identity: true, notNull: true),
            .init(name: "v", type: "text", notNull: true),
        ], primaryKey: ["id"])
        XCTAssertEqual(sql, "CREATE TABLE IF NOT EXISTS \"s\".\"t\" (\"id\" bigint GENERATED BY DEFAULT AS IDENTITY, "
                       + "\"v\" text NOT NULL, PRIMARY KEY (\"id\"))")
    }

    func testDuplicateKeySQLIgnoresNullKeys() {
        XCTAssertEqual(CrossDBCopy.duplicateKeySQL(inTemp: "_t", conflictColumns: ["a", "b"]),
                       "SELECT count(*)::int FROM (SELECT 1 FROM \"_t\" WHERE \"a\" IS NOT NULL AND \"b\" IS NOT NULL "
                       + "GROUP BY \"a\", \"b\" HAVING count(*) > 1) d")
    }

    func testUpsertOverridingSystemValue() {
        let sql = CrossDBCopy.upsertSQL(fromTemp: "_t", schema: "s", table: "t", targetColumns: ["id", "v"],
                                        conflictColumns: ["id"], overridingSystemValue: true)
        XCTAssertTrue(sql.hasPrefix("INSERT INTO \"s\".\"t\" (\"id\", \"v\") OVERRIDING SYSTEM VALUE SELECT"))
    }

    func testTLSMatchesConnectionServiceSemantics() {
        XCTAssertNil(CrossDBCopy.tlsPolicy(for: .disable))
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .allow)?.required, false)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .prefer)?.required, false)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .prefer)?.verification, CertificateVerification.none)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .require)?.required, true)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .require)?.verification, CertificateVerification.none)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .verifyCA)?.verification, .noHostnameVerification)
        XCTAssertEqual(CrossDBCopy.tlsPolicy(for: .verifyFull)?.verification, .fullVerification)
    }

    // MARK: E2E

    func testUpsertWithoutConflictColumnsFailsFast() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let plan = CrossDBCopy.Plan(
            source: TableNode(schema: "public", name: "x", kind: .table, columns: [col("id")]),
            sourceClient: db.client, target: .existing(db.client), targetSchema: "public", targetTable: "x",
            strategy: .upsert, mappings: [map("id")])
        do { _ = try await CrossDBCopy.execute(plan: plan); XCTFail("expected error") }
        catch let e as CrossDBCopy.CopyError { XCTAssertEqual(e, .missingConflictColumns) }
    }

    func testAutoCreateKeepsIdentityAndAdvancesSequence() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); let t = TestDB.uniqueTag()
        await db.dropSchemas(s, t)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)"; CREATE SCHEMA "\(t)";
            CREATE TYPE "\(s)".mood AS ENUM ('ok', 'sad');
            CREATE TABLE "\(s)".src (id serial PRIMARY KEY, m "\(s)".mood NOT NULL, v text);
            INSERT INTO "\(s)".src (m, v) SELECT 'ok', 'r' || g FROM generate_series(1, 5) g
            """)
            let src = TableNode(schema: s, name: "src", kind: .table,
                                columns: [col("id"), col("m", "\(s).mood"), col("v", "text")], primaryKey: ["id"])
            let plan = CrossDBCopy.Plan(
                source: src, sourceClient: db.client, target: .existing(db.client),
                targetSchema: t, targetTable: "dst", strategy: .append,
                mappings: [map("id"), map("m", "\(s).mood"), map("v", "text")], autoCreate: true)
            let stats = try await CrossDBCopy.execute(plan: plan)
            XCTAssertEqual(stats.rowsCopied, 5)
            XCTAssertEqual(stats.sequencesAdvanced, 1)
            try await db.exec("INSERT INTO \"\(t)\".dst (m, v) VALUES ('ok', 'new')")
            let newID = try await db.scalarInt("SELECT id FROM \"\(t)\".dst WHERE v = 'new'")
            XCTAssertEqual(newID, 6, "identity continues after the copied max")
            let isIdentity = try await db.scalarBool("""
            SELECT attidentity = 'd' FROM pg_attribute WHERE attrelid = '"\(t)".dst'::regclass AND attname = 'id'
            """)
            XCTAssertTrue(isIdentity)
        } catch { await db.dropSchemas(s, t); throw error }
        await db.dropSchemas(s, t)
    }

    func testAppendIntoSerialTableAdvancesSequence() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); let t = TestDB.uniqueTag()
        await db.dropSchemas(s, t)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)"; CREATE SCHEMA "\(t)";
            CREATE TABLE "\(s)".src (id int PRIMARY KEY, v text);
            INSERT INTO "\(s)".src VALUES (10, 'a'), (20, 'b');
            CREATE TABLE "\(t)".dst (id serial PRIMARY KEY, v text)
            """)
            let src = TableNode(schema: s, name: "src", kind: .table, columns: [col("id"), col("v", "text")])
            let plan = CrossDBCopy.Plan(source: src, sourceClient: db.client, target: .existing(db.client),
                                        targetSchema: t, targetTable: "dst", strategy: .append,
                                        mappings: [map("id"), map("v", "text")])
            _ = try await CrossDBCopy.execute(plan: plan)
            try await db.exec("INSERT INTO \"\(t)\".dst (v) VALUES ('next')")
            let next = try await db.scalarInt("SELECT id FROM \"\(t)\".dst WHERE v = 'next'")
            XCTAssertEqual(next, 21)
        } catch { await db.dropSchemas(s, t); throw error }
        await db.dropSchemas(s, t)
    }

    func testUpsertWithDuplicateSourceKeysFailsClearly() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); let t = TestDB.uniqueTag()
        await db.dropSchemas(s, t)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)"; CREATE SCHEMA "\(t)";
            CREATE TABLE "\(s)".src (k int, v text);
            INSERT INTO "\(s)".src VALUES (1, 'a'), (1, 'b'), (2, 'c'), (NULL, 'x'), (NULL, 'y');
            CREATE TABLE "\(t)".dst (k int UNIQUE, v text);
            INSERT INTO "\(t)".dst VALUES (2, 'keep')
            """)
            let src = TableNode(schema: s, name: "src", kind: .table, columns: [col("k"), col("v", "text")])
            let plan = CrossDBCopy.Plan(source: src, sourceClient: db.client, target: .existing(db.client),
                                        targetSchema: t, targetTable: "dst", strategy: .upsert,
                                        mappings: [map("k"), map("v", "text")], conflictColumns: ["k"])
            do {
                _ = try await CrossDBCopy.execute(plan: plan)
                XCTFail("duplicate keys must fail")
            } catch let e as CrossDBCopy.CopyError {
                XCTAssertEqual(e, .duplicateSourceKeys(groups: 1, columns: ["k"]))
            }
            let v = try await db.scalarString("SELECT v FROM \"\(t)\".dst WHERE k = 2")
            XCTAssertEqual(v, "keep", "rolled back")
        } catch { await db.dropSchemas(s, t); throw error }
        await db.dropSchemas(s, t)
    }
}
