import XCTest
import PostgresNIO
@testable import pgBrain

/// E2E: RETURNING splice-back, optimistic concurrency, ctid-addressed edits
/// and the Preview SQL script.
final class C_UpdateApplierReturningTests: XCTestCase {

    private func col(_ t: TableNode, _ name: String) -> ColumnNode {
        t.columns.first { $0.name == name }!
    }

    /// `n (id pk, amount numeric(10,2), code char(4), touched int)` with a
    /// trigger bumping `touched` on every UPDATE.
    private func makeNormalising(_ db: TestDB, _ s: String) async throws -> TableNode {
        try await db.exec("""
        CREATE SCHEMA "\(s)";
        CREATE TABLE "\(s)".n (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, amount numeric(10,2), code char(4), touched int DEFAULT 0)
        """)
        // One statement per call: TestDB.exec splits on ';', which would cut
        // the function body apart.
        _ = try await db.client.query(PostgresQuery(unsafeSQL: """
        CREATE FUNCTION "\(s)".bump() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.touched := OLD.touched + 1; RETURN NEW; END $$
        """))
        try await db.exec("""
        CREATE TRIGGER bump BEFORE UPDATE ON "\(s)".n FOR EACH ROW EXECUTE FUNCTION "\(s)".bump();
        INSERT INTO "\(s)".n (amount, code) VALUES (10, 'ab')
        """)
        return TableNode(schema: s, name: "n", kind: .table, columns: [
            ColumnNode(name: "id", typeName: "integer", nullable: false, ordinal: 0),
            ColumnNode(name: "amount", typeName: "numeric(10,2)", nullable: true, ordinal: 1),
            ColumnNode(name: "code", typeName: "character(4)", nullable: true, ordinal: 2),
            ColumnNode(name: "touched", typeName: "integer", nullable: true, ordinal: 3),
        ], primaryKey: ["id"])
    }

    func testUpdateAndInsertReturnWhatTheServerStored() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNormalising(db, s)
            let loaded: [[String?]] = [["1", "10.00", "ab", "0"]]
            let outcome = try await UpdateApplier.apply(
                edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "amount"), value: .literal("1.5"))])],
                inserts: [.init(cells: [.init(column: col(t, "amount"), value: .literal("2")),
                                        .init(column: col(t, "code"), value: .literal("x"))])],
                table: t, originalRows: loaded, client: db.client)
            XCTAssertEqual(outcome.updatedRows[0], ["1", "1.50", "ab", "1"],
                           "typed 1.5 comes back as numeric(10,2) 1.50, trigger-set touched = 1")
            XCTAssertEqual(outcome.insertedRows.count, 1)
            XCTAssertEqual(outcome.insertedRows.first?[1], "2.00")
            XCTAssertEqual(outcome.insertedRows.first?[2], "x", "char(n)::text drops the padding, like the grid's fetch")
            XCTAssertEqual(outcome.insertedRows.first?[0] ?? nil, "2", "identity value comes back")
            XCTAssertNotNil(outcome.insertedRows.first?[0] ?? nil, "identity value comes back")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    /// Someone else changed the very column we edited → stale, nothing saved.
    func testConcurrentChangeToEditedColumnIsDetected() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNormalising(db, s)
            let loaded: [[String?]] = [["1", "10.00", "ab", "0"]]
            try await db.exec("UPDATE \"\(s)\".n SET amount = 99 WHERE id = 1")
            await XCTAssertThrowsErrorAsync(
                try await UpdateApplier.apply(
                    edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "amount"), value: .literal("11"))])],
                    table: t, originalRows: loaded, client: db.client)
            ) {
                XCTAssertEqual($0 as? UpdateApplier.Failure, .staleRow("id=1"))
            }
            let amount = try await db.scalarString("SELECT amount::text FROM \"\(s)\".n WHERE id = 1")
            XCTAssertEqual(amount, "99.00", "the other session's value survives")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    /// A concurrent change to a column we did *not* touch doesn't block us.
    func testConcurrentChangeToOtherColumnStillApplies() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNormalising(db, s)
            let loaded: [[String?]] = [["1", "10.00", "ab", "0"]]
            try await db.exec("UPDATE \"\(s)\".n SET code = 'zz' WHERE id = 1")
            let outcome = try await UpdateApplier.apply(
                edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "amount"), value: .expression("amount + 1"))])],
                table: t, originalRows: loaded, client: db.client)
            XCTAssertEqual(outcome.updatedRows[0]?[1], "11.00")
            XCTAssertEqual(outcome.updatedRows[0]?[2], "zz", "splice-back carries the other session's change too")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    func testNullOriginalMatchesWithIsNotDistinctFrom() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNormalising(db, s)
            try await db.exec("UPDATE \"\(s)\".n SET amount = NULL WHERE id = 1")
            let loaded: [[String?]] = [["1", nil, "ab", "1"]]
            let outcome = try await UpdateApplier.apply(
                edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "amount"), value: .literal("3"))])],
                table: t, originalRows: loaded, client: db.client)
            XCTAssertEqual(outcome.updatedRows[0]?[1], "3.00")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    /// A server-side failure must reach the caller as that failure (not as
    /// a generic cancellation) and roll the batch back.
    func testServerErrorSurfacesAndRollsBack() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNormalising(db, s)
            let loaded: [[String?]] = [["1", "10.00", "ab", "0"]]
            await XCTAssertThrowsErrorAsync(
                try await UpdateApplier.apply(
                    edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "amount"), value: .literal("5"))])],
                    inserts: [.init(cells: [.init(column: col(t, "id"), value: .literal("1"))])],
                    table: t, originalRows: loaded, client: db.client)
            ) {
                XCTAssertFalse($0 is CancellationError, "got \($0)")
                XCTAssertTrue(PostgresErrorMessage.describe($0).contains("duplicate key"), PostgresErrorMessage.describe($0))
            }
            let amount = try await db.scalarString("SELECT amount::text FROM \"\(s)\".n WHERE id = 1")
            XCTAssertEqual(amount, "10.00")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    // MARK: - ctid

    private func makeNoPK(_ db: TestDB, _ s: String) async throws -> TableNode {
        try await db.exec("""
        CREATE SCHEMA "\(s)";
        CREATE TABLE "\(s)".d (id int, label text);
        INSERT INTO "\(s)".d VALUES (1, 'same'), (1, 'same'), (2, 'other')
        """)
        return TableNode(schema: s, name: "d", kind: .table, columns: [
            ColumnNode(name: "id", typeName: "integer", nullable: true, ordinal: 0),
            ColumnNode(name: "label", typeName: "text", nullable: true, ordinal: 1),
        ], primaryKey: [])
    }

    /// Two identical rows: an edit and a delete each hit exactly one of them.
    func testCtidAddressesOneOfTwoIdenticalRows() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNoPK(db, s)
            let page = try await RowsFetcher.page(offset: 0, pageSize: 10, from: t, client: db.client)
            XCTAssertEqual(page.rows[0], page.rows[1])
            let outcome = try await UpdateApplier.apply(
                edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "label"), value: .literal("changed"))])],
                inserts: [.init(cells: [.init(column: col(t, "id"), value: .literal("3"))])],
                deletes: [.init(rowIndex: 2)],
                table: t, originalRows: page.rows, rowLocators: page.rowLocators, client: db.client)
            let changed = try await db.scalarInt("SELECT count(*) FROM \"\(s)\".d WHERE label = 'changed'")
            let same = try await db.scalarInt("SELECT count(*) FROM \"\(s)\".d WHERE label = 'same'")
            let twos = try await db.scalarInt("SELECT count(*) FROM \"\(s)\".d WHERE id = 2")
            XCTAssertEqual(changed, 1)
            XCTAssertEqual(same, 1)
            XCTAssertEqual(twos, 0)
            let newLoc = try XCTUnwrap(outcome.updatedLocators[0])
            XCTAssertNotEqual(newLoc, page.rowLocators?[0] ?? nil, "an UPDATE moves the row; the new ctid comes back")
            XCTAssertNotNil(outcome.insertedLocators.first ?? nil)
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    /// Once another session updates the row its ctid is gone: the edit fails
    /// as stale instead of touching anything.
    func testStaleCtidIsRejected() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            let t = try await makeNoPK(db, s)
            let page = try await RowsFetcher.page(offset: 0, pageSize: 10, from: t, client: db.client)
            try await db.exec("UPDATE \"\(s)\".d SET id = id WHERE id = 2")
            await XCTAssertThrowsErrorAsync(
                try await UpdateApplier.apply(
                    edits: [.init(rowIndex: 2, cells: [.init(column: col(t, "label"), value: .literal("x"))])],
                    table: t, originalRows: page.rows, rowLocators: page.rowLocators, client: db.client)
            ) {
                guard case UpdateApplier.Failure.staleRow(let label) = $0 else { return XCTFail("got \($0)") }
                XCTAssertTrue(label.hasPrefix("ctid="))
            }
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    func testMissingLocatorIsAnError() {
        let t = TableNode(schema: "s", name: "d", kind: .table, columns: [
            ColumnNode(name: "id", typeName: "integer", nullable: true, ordinal: 0),
        ], primaryKey: [])
        XCTAssertThrowsError(try UpdateApplier.plan(
            edits: [.init(rowIndex: 0, cells: [.init(column: t.columns[0], value: .literal("1"))])],
            table: t, originalRows: [["0"]], rowLocators: nil)
        ) { XCTAssertEqual($0 as? UpdateApplier.Failure, .missingRowLocator(0)) }
    }

    // MARK: - Preview

    func testPreviewScriptInlinesBindsInOrder() throws {
        let t = TableNode(schema: "app", name: "users", kind: .table, columns: [
            ColumnNode(name: "id", typeName: "integer", nullable: false, ordinal: 0),
            ColumnNode(name: "email", typeName: "text", nullable: true, ordinal: 1),
            ColumnNode(name: "seen", typeName: "timestamp with time zone", nullable: true, ordinal: 2),
        ], primaryKey: ["id"])
        let statements = try UpdateApplier.plan(
            edits: [.init(rowIndex: 0, cells: [
                .init(column: t.columns[1], value: .literal("o'brien@example.com")),
                .init(column: t.columns[2], value: .expression("now()")),
            ])],
            inserts: [.init(cells: [.init(column: t.columns[1], value: .literal(nil))])],
            deletes: [.init(rowIndex: 1)],
            table: t, originalRows: [["7", "old@example.com", nil], ["8", "x", nil]])
        XCTAssertEqual(statements.map(\.kind), [.update(rowIndex: 0), .insert(index: 0), .delete(rowIndex: 1)])
        XCTAssertEqual(statements[0].binds, ["o'brien@example.com", "7", "old@example.com", nil])
        let script = UpdateApplier.previewScript(statements)
        XCTAssertTrue(script.hasPrefix("BEGIN;\n"))
        XCTAssertTrue(script.hasSuffix("COMMIT;"))
        XCTAssertTrue(script.contains(#"SET "email" = 'o''brien@example.com'::text,"#), script)
        XCTAssertTrue(script.contains(#""seen" = (now()"#), script)
        XCTAssertTrue(script.contains(#"WHERE "id" = '7'::integer"#), script)
        XCTAssertTrue(script.contains(#""email"::text IS NOT DISTINCT FROM 'old@example.com'::text"#), script)
        XCTAssertTrue(script.contains(#""seen"::text IS NOT DISTINCT FROM NULL::text"#), script)
        XCTAssertTrue(script.contains(#"INSERT INTO "app"."users" ("email")"#), script)
        XCTAssertTrue(script.contains(#"DELETE FROM "app"."users""#) && script.contains(#"WHERE "id" = '8'::integer;"#), script)
        XCTAssertEqual(UpdateApplier.inlineBinds("a = $1 AND b = '$2' AND c = $10", ["x", "y"]), "a = 'x' AND b = '$2' AND c = $10")
    }

    // MARK: - Composite foreign keys

    func testCompositeForeignKeyCatalogAndWhere() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)";
            CREATE TABLE "\(s)".parent (a int, b text, PRIMARY KEY (a, b));
            CREATE TABLE "\(s)".child (id int PRIMARY KEY, pa int, pb text, other int REFERENCES "\(s)".child(id),
                FOREIGN KEY (pb, pa) REFERENCES "\(s)".parent (b, a));
            INSERT INTO "\(s)".parent VALUES (1, 'x')
            """)
            let keys = try await ForeignKeyResolver.fetch(client: db.client, schema: s, table: "child")
            XCTAssertEqual(keys.count, 2)
            let composite = try XCTUnwrap(ForeignKeyResolver.key(for: "pa", in: keys))
            XCTAssertEqual(composite.localColumns, ["pb", "pa"])
            XCTAssertEqual(composite.refColumns, ["b", "a"])
            XCTAssertEqual(ForeignKeyResolver.key(for: "other", in: keys)?.refTable, "child")
            let clause = ForeignKeyResolver.whereClause(for: composite, values: ["x", "1"], refTypes: ["a": "integer", "b": "text"])
            XCTAssertEqual(clause, #""b" = 'x'::text AND "a" = '1'::integer"#)
            let hits = try await db.scalarInt("SELECT count(*) FROM \"\(s)\".parent WHERE \(clause)")
            XCTAssertEqual(hits, 1)
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }
}
