import XCTest
import PostgresNIO
@testable import pgBrain

/// UPDATE must touch exactly one row, a ctid DELETE must still see the row
/// the grid showed, and suppressed INSERTs keep later results aligned.
final class F2_UpdateApplierIdentityTests: XCTestCase {

    private func col(_ t: TableNode, _ name: String) -> ColumnNode {
        t.columns.first { $0.name == name }!
    }

    func testUpdateMatchingInheritedDuplicateIsRejected() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)";
            CREATE TABLE "\(s)".p (id int PRIMARY KEY, v text);
            CREATE TABLE "\(s)".c () INHERITS ("\(s)".p);
            INSERT INTO "\(s)".p VALUES (1, 'a');
            INSERT INTO "\(s)".c VALUES (1, 'a')
            """)
            let t = TableNode(schema: s, name: "p", kind: .table, columns: [
                ColumnNode(name: "id", typeName: "integer", nullable: false, ordinal: 0),
                ColumnNode(name: "v", typeName: "text", nullable: true, ordinal: 1),
            ], primaryKey: ["id"])
            await XCTAssertThrowsErrorAsync(
                try await UpdateApplier.apply(
                    edits: [.init(rowIndex: 0, cells: [.init(column: col(t, "v"), value: .literal("z"))])],
                    table: t, originalRows: [["1", "a"]], client: db.client)
            ) {
                XCTAssertEqual($0 as? UpdateApplier.Failure, .ambiguousRow("id=1", 2))
            }
            let changed = try await db.scalarInt("SELECT count(*)::int FROM \"\(s)\".p WHERE v = 'z'")
            XCTAssertEqual(changed, 0, "the whole batch rolled back")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    func testSuppressedInsertKeepsLaterResultsAligned() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)";
            CREATE TABLE "\(s)".t (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text)
            """)
            _ = try await db.client.query(PostgresQuery(unsafeSQL: """
            CREATE FUNCTION "\(s)".skip() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.v = 'skip' THEN RETURN NULL; END IF; RETURN NEW; END $$
            """))
            try await db.exec("""
            CREATE TRIGGER skip BEFORE INSERT ON "\(s)".t FOR EACH ROW EXECUTE FUNCTION "\(s)".skip()
            """)
            let t = TableNode(schema: s, name: "t", kind: .table, columns: [
                ColumnNode(name: "id", typeName: "integer", nullable: false, ordinal: 0),
                ColumnNode(name: "v", typeName: "text", nullable: true, ordinal: 1),
            ], primaryKey: ["id"])
            let outcome = try await UpdateApplier.apply(
                edits: [],
                inserts: [.init(cells: [.init(column: col(t, "v"), value: .literal("skip"))]),
                          .init(cells: [.init(column: col(t, "v"), value: .literal("keep"))])],
                table: t, originalRows: [], client: db.client)
            XCTAssertEqual(outcome.insertedRowsByDraft.count, 2)
            XCTAssertNil(outcome.insertedRowsByDraft[0])
            XCTAssertEqual(outcome.insertedRowsByDraft[1]?[1], "keep")
            XCTAssertTrue(outcome.insertedRows.isEmpty,
                          "the positional view never shifts 'keep' onto the first draft")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    func testCtidDeleteRefusesAReusedSlot() async throws {
        let db = try await TestDB.connectOrSkip(); defer { db.shutdown() }
        let s = TestDB.uniqueTag(); await db.dropSchemas(s)
        do {
            try await db.exec("""
            CREATE SCHEMA "\(s)";
            CREATE TABLE "\(s)".d (id int, label text) WITH (autovacuum_enabled = off);
            INSERT INTO "\(s)".d VALUES (1, 'original')
            """)
            let t = TableNode(schema: s, name: "d", kind: .table, columns: [
                ColumnNode(name: "id", typeName: "integer", nullable: true, ordinal: 0),
                ColumnNode(name: "label", typeName: "text", nullable: true, ordinal: 1),
            ], primaryKey: [])
            let page = try await RowsFetcher.page(offset: 0, pageSize: 10, from: t, client: db.client)
            let loaded = try XCTUnwrap(page.rowLocators?[0] ?? nil)
            try await db.exec("DELETE FROM \"\(s)\".d")
            try await db.exec("VACUUM \"\(s)\".d")
            try await db.exec("INSERT INTO \"\(s)\".d VALUES (2, 'intruder')")
            let now = try await db.scalarString("SELECT ctid::text || '@' || tableoid::oid::text FROM \"\(s)\".d")
            guard now == loaded else {
                await db.dropSchemas(s)
                throw XCTSkip("server didn't reuse the slot (\(now) vs \(loaded))")
            }
            await XCTAssertThrowsErrorAsync(
                try await UpdateApplier.apply(
                    edits: [], deletes: [.init(rowIndex: 0)],
                    table: t, originalRows: page.rows, rowLocators: page.rowLocators, client: db.client)
            ) {
                guard case UpdateApplier.Failure.staleRow = $0 else { return XCTFail("got \($0)") }
            }
            let left = try await db.scalarInt("SELECT count(*)::int FROM \"\(s)\".d")
            XCTAssertEqual(left, 1, "the unrelated row in the reused slot survives")
        } catch { await db.dropSchemas(s); throw error }
        await db.dropSchemas(s)
    }

    func testCtidDeletePlanGuardsEveryColumn() throws {
        let t = TableNode(schema: "s", name: "d", kind: .table, columns: [
            ColumnNode(name: "id", typeName: "integer", nullable: true, ordinal: 0),
            ColumnNode(name: "label", typeName: "text", nullable: true, ordinal: 1),
        ], primaryKey: [])
        let plan = try UpdateApplier.plan(
            edits: [], deletes: [.init(rowIndex: 0)], table: t,
            originalRows: [["1", nil]], rowLocators: ["(0,1)@123"])
        XCTAssertEqual(plan.count, 1)
        XCTAssertTrue(plan[0].sql.contains(#""id"::text IS NOT DISTINCT FROM $3::text"#), plan[0].sql)
        XCTAssertTrue(plan[0].sql.contains(#""label"::text IS NOT DISTINCT FROM $4::text"#), plan[0].sql)
        XCTAssertEqual(plan[0].binds, ["(0,1)", "123", "1", nil])
    }
}
