import Foundation
import NIOCore
import NIOSSL
import PostgresNIO

/// Pipes a table (or arbitrary subset of columns) from one Postgres
/// connection to another. Bytes never touch disk — rows stream from
/// `sourceClient` via a typed `SELECT` and land in `targetClient`'s
/// `copyFrom` writer using the Postgres COPY TEXT format.
///
/// For "extreme" cases (multi-million-row tables, slow client links) this
/// is the right shape: row sequence stays lazy on both ends, the worst-case
/// memory hit is a single 64KB ByteBuffer.
enum CrossDBCopy {
    enum Strategy: String, CaseIterable, Identifiable {
        case append, truncateAndInsert, upsert
        var id: String { rawValue }
        var uiLabel: String {
            switch self {
            case .append: return "Append (keep existing rows)"
            case .truncateAndInsert: return "Truncate then insert"
            case .upsert: return "Upsert (insert or update on conflict)"
            }
        }
        /// The upsert strategy needs a conflict target (the columns whose
        /// collision triggers an UPDATE instead of a failed INSERT).
        var needsConflictColumns: Bool { self == .upsert }
    }

    struct Mapping: Sendable {
        let sourceColumn: ColumnNode
        let targetColumnName: String
    }

    struct Plan: Sendable {
        let source: TableNode
        let sourceClient: PostgresClient
        let target: TargetEndpoint
        let targetSchema: String
        let targetTable: String
        let strategy: Strategy
        let mappings: [Mapping]
        /// Create the target table (from the source column types) when it
        /// doesn't already exist, instead of failing the copy.
        let autoCreate: Bool
        /// Conflict-target columns (target names) for `.upsert`. Ignored by
        /// other strategies.
        let conflictColumns: [String]

        init(source: TableNode, sourceClient: PostgresClient, target: TargetEndpoint,
             targetSchema: String, targetTable: String, strategy: Strategy,
             mappings: [Mapping], autoCreate: Bool = false, conflictColumns: [String] = []) {
            self.source = source
            self.sourceClient = sourceClient
            self.target = target
            self.targetSchema = targetSchema
            self.targetTable = targetTable
            self.strategy = strategy
            self.mappings = mappings
            self.autoCreate = autoCreate
            self.conflictColumns = conflictColumns
        }
    }

    /// A target column for auto-create, after mapping the source type onto
    /// something the target database actually has.
    struct ColumnSpec: Equatable, Sendable {
        let name: String
        let type: String
        var identity: Bool = false
        var notNull: Bool = false
    }

    // MARK: - SQL builders (pure)

    /// `CREATE TABLE IF NOT EXISTS schema.table (target_col source_type, …)` —
    /// each target column adopts its source column's declared type verbatim.
    static func createTableSQL(schema: String, table: String, mappings: [Mapping]) -> String {
        createTableSQL(schema: schema, table: table,
                       columns: mappings.map { ColumnSpec(name: $0.targetColumnName, type: $0.sourceColumn.typeName) },
                       primaryKey: [])
    }

    static func createTableSQL(schema: String, table: String, columns: [ColumnSpec], primaryKey: [String]) -> String {
        var defs = columns.map { c -> String in
            var d = "\(SQLIdent.quote(c.name)) \(c.type)"
            // BY DEFAULT (not ALWAYS) so the copied explicit values are accepted
            // while later inserts keep auto-numbering.
            if c.identity { d += " GENERATED BY DEFAULT AS IDENTITY" }
            else if c.notNull { d += " NOT NULL" }
            return d
        }
        if !primaryKey.isEmpty {
            defs.append("PRIMARY KEY (\(primaryKey.map { SQLIdent.quote($0) }.joined(separator: ", ")))")
        }
        return "CREATE TABLE IF NOT EXISTS \(SQLIdent.qualified(schema: schema, name: table)) (\(defs.joined(separator: ", ")))"
    }

    /// `INSERT INTO target (cols) SELECT cols FROM temp ON CONFLICT (keys) …` —
    /// non-key columns are refreshed from `EXCLUDED`; if every column is part of
    /// the conflict key there's nothing to update, so it degrades to DO NOTHING.
    static func upsertSQL(fromTemp tempTable: String, schema: String, table: String,
                          targetColumns: [String], conflictColumns: [String],
                          overridingSystemValue: Bool = false) -> String {
        let target = SQLIdent.qualified(schema: schema, name: table)
        let colList = targetColumns.map { SQLIdent.quote($0) }.joined(separator: ", ")
        let conflictList = conflictColumns.map { SQLIdent.quote($0) }.joined(separator: ", ")
        let updateCols = targetColumns.filter { !conflictColumns.contains($0) }
        let action: String
        if updateCols.isEmpty {
            action = "DO NOTHING"
        } else {
            let sets = updateCols.map { "\(SQLIdent.quote($0)) = EXCLUDED.\(SQLIdent.quote($0))" }
                .joined(separator: ", ")
            action = "DO UPDATE SET \(sets)"
        }
        let overriding = overridingSystemValue ? " OVERRIDING SYSTEM VALUE" : ""
        return "INSERT INTO \(target) (\(colList))\(overriding) SELECT \(colList) FROM \(SQLIdent.quote(tempTable)) "
            + "ON CONFLICT (\(conflictList)) \(action)"
    }

    /// Rows sharing a conflict key would make `ON CONFLICT DO UPDATE` fail with
    /// "cannot affect row a second time" — count those groups up front so the
    /// user gets a clear error. NULL keys never conflict, so they're excluded.
    static func duplicateKeySQL(inTemp tempTable: String, conflictColumns: [String]) -> String {
        let cols = conflictColumns.map { SQLIdent.quote($0) }
        let notNull = cols.map { "\($0) IS NOT NULL" }.joined(separator: " AND ")
        return "SELECT count(*)::int FROM (SELECT 1 FROM \(SQLIdent.quote(tempTable)) WHERE \(notNull) "
            + "GROUP BY \(cols.joined(separator: ", ")) HAVING count(*) > 1) d"
    }

    /// Either an already-leased client (when the target is currently open in
    /// another window) or a `Connection` we need to bring up a transient
    /// client for.
    enum TargetEndpoint {
        case existing(PostgresClient)
        case transient(Connection, password: String)
    }

    struct Stats: Sendable {
        var rowsCopied: Int
        var elapsed: TimeInterval
        /// Type substitutions made while auto-creating the target table.
        var warnings: [String] = []
        var sequencesAdvanced: Int = 0
    }

    enum CopyError: LocalizedError, Equatable {
        case transientClientGone
        case decodeFailed(column: String, row: Int)
        case missingConflictColumns
        case conflictColumnNotCopied(String)
        case duplicateSourceKeys(groups: Int, columns: [String])

        var errorDescription: String? {
            switch self {
            case .transientClientGone:
                return "Lost transient connection during copy."
            case .decodeFailed(let column, let row):
                return "Couldn't read column \"\(column)\" of source row \(row) — copy aborted, nothing was written."
            case .missingConflictColumns:
                return "Upsert needs at least one conflict (key) column."
            case .conflictColumnNotCopied(let name):
                return "Conflict column \"\(name)\" isn't among the copied columns."
            case .duplicateSourceKeys(let groups, let columns):
                return "The source has \(groups) key value\(groups == 1 ? "" : "s") that appear more than once in "
                    + "(\(columns.joined(separator: ", "))) — upsert can't apply two rows to the same target row. "
                    + "Deduplicate the source or pick different conflict columns."
            }
        }
    }

    static func execute(
        plan: Plan,
        tracker: OperationsCenter? = nil,
        operationID: UUID? = nil
    ) async throws -> Stats {
        let started = Date()
        let qualifiedSource = SQLIdent.qualified(schema: plan.source.schema, name: plan.source.name)
        let projection = plan.mappings
            .map { "\(SQLIdent.quote($0.sourceColumn.name))::text" }
            .joined(separator: ", ")
        let selectSQL = "SELECT \(projection) FROM \(qualifiedSource)"

        let targetColumns = plan.mappings.map { $0.targetColumnName }
        if plan.strategy == .upsert {
            guard !plan.conflictColumns.isEmpty else { throw CopyError.missingConflictColumns }
            if let missing = plan.conflictColumns.first(where: { !targetColumns.contains($0) }) {
                throw CopyError.conflictColumnNotCopied(missing)
            }
        }
        let rowCount = RowCountBox()
        var warnings: [String] = []
        var advanced = 0

        try await withTargetClient(plan.target) { targetClient in
            try await plan.sourceClient.withConnection { sourceConn in
                if let opID = operationID, let tracker {
                    let pid = try await OperationsHelpers.fetchBackendPID(sourceConn, logger: pgbrainQuietLogger)
                    let cancel: @Sendable () async -> Void = { [weak sourceClient = plan.sourceClient] in
                        guard let sourceClient else { return }
                        _ = try? await sourceClient.withConnection { sister in
                            _ = try await sister.query(
                                PostgresQuery(unsafeSQL: "SELECT pg_cancel_backend(\(pid))"),
                                logger: pgbrainQuietLogger
                            )
                        }
                    }
                    Task { @MainActor in
                        tracker.attachCancellation(toOperationID: opID, pid: pid, handler: cancel)
                    }
                }

                // Read the source catalog before the row stream starts — one
                // connection can't serve a second query mid-stream.
                let sourceInfo = plan.autoCreate ? try await sourceColumnInfo(sourceConn, plan: plan) : []

                try await targetClient.withConnection { targetConn in
                    _ = try await targetConn.query(PostgresQuery(unsafeSQL: "BEGIN"), logger: pgbrainQuietLogger)
                    do {
                        _ = try await targetConn.query(
                            PostgresQuery(unsafeSQL: "SET LOCAL search_path = \(SQLIdent.quote(plan.targetSchema))"),
                            logger: pgbrainQuietLogger
                        )
                        let qualifiedTarget = SQLIdent.qualified(schema: plan.targetSchema, name: plan.targetTable)
                        if plan.autoCreate {
                            let (specs, w) = try await resolveTargetColumns(targetConn, sourceInfo)
                            warnings = w
                            let pk = autoCreatePrimaryKey(plan)
                            _ = try await targetConn.query(
                                PostgresQuery(unsafeSQL: createTableSQL(
                                    schema: plan.targetSchema, table: plan.targetTable, columns: specs, primaryKey: pk)),
                                logger: pgbrainQuietLogger
                            )
                        }
                        // Upsert stages into a temp table (dropped on commit) so we
                        // can INSERT … ON CONFLICT from it afterwards; other
                        // strategies copy straight into the table.
                        let copyTarget: String
                        var tempName: String? = nil
                        if plan.strategy == .upsert {
                            let tmp = "_pgb_copy_" + UUID().uuidString.prefix(8).lowercased()
                            _ = try await targetConn.query(
                                PostgresQuery(unsafeSQL: "CREATE TEMP TABLE \(SQLIdent.quote(tmp)) (LIKE \(qualifiedTarget) INCLUDING DEFAULTS) ON COMMIT DROP"),
                                logger: pgbrainQuietLogger
                            )
                            tempName = tmp
                            copyTarget = tmp
                        } else {
                            if plan.strategy == .truncateAndInsert {
                                _ = try await targetConn.query(
                                    PostgresQuery(unsafeSQL: "TRUNCATE \(qualifiedTarget)"),
                                    logger: pgbrainQuietLogger
                                )
                            }
                            copyTarget = plan.targetTable
                        }
                        try await targetConn.copyFrom(
                            table: copyTarget,
                            columns: targetColumns,
                            format: .text(.init()),
                            logger: pgbrainQuietLogger
                        ) { writer in
                            var buffer = ByteBufferAllocator().buffer(capacity: 64 * 1024)
                            let stream = try await sourceConn.query(
                                PostgresQuery(unsafeSQL: selectSQL),
                                logger: pgbrainQuietLogger
                            )
                            for try await row in stream {
                                try Task.checkCancellation()
                                let random = PostgresRandomAccessRow(row)
                                for i in 0..<plan.mappings.count {
                                    if i > 0 { buffer.writeString("\t") }
                                    let cell = random[i]
                                    if cell.bytes == nil {
                                        buffer.writeString("\\N")
                                        continue
                                    }
                                    // Every column is projected `::text`; a decode
                                    // failure must abort, never become a silent NULL.
                                    guard let v = try? cell.decode(String.self, context: .default) else {
                                        throw CopyError.decodeFailed(column: plan.mappings[i].sourceColumn.name,
                                                                     row: rowCount.value + 1)
                                    }
                                    buffer.writeString(Importer.copyTextEscape(v))
                                }
                                buffer.writeString("\n")
                                rowCount.add(1)
                                if buffer.readableBytes >= 64 * 1024 {
                                    try await writer.write(buffer)
                                    buffer.clear()
                                }
                            }
                            if buffer.readableBytes > 0 {
                                try await writer.write(buffer)
                            }
                        }
                        if plan.strategy == .upsert, let tempName {
                            let dupes = try await scalarInt(targetConn, PostgresQuery(unsafeSQL:
                                duplicateKeySQL(inTemp: tempName, conflictColumns: plan.conflictColumns)))
                            if dupes > 0 {
                                throw CopyError.duplicateSourceKeys(groups: dupes, columns: plan.conflictColumns)
                            }
                            let overriding = try await hasAlwaysIdentity(targetConn, qualified: qualifiedTarget,
                                                                         columns: targetColumns)
                            _ = try await targetConn.query(
                                PostgresQuery(unsafeSQL: upsertSQL(
                                    fromTemp: tempName, schema: plan.targetSchema, table: plan.targetTable,
                                    targetColumns: targetColumns, conflictColumns: plan.conflictColumns,
                                    overridingSystemValue: overriding)),
                                logger: pgbrainQuietLogger
                            )
                        }
                        advanced = try await advanceSequences(targetConn, qualified: qualifiedTarget, columns: targetColumns)
                        _ = try await targetConn.query(PostgresQuery(unsafeSQL: "COMMIT"), logger: pgbrainQuietLogger)
                    } catch {
                        _ = try? await targetConn.query(PostgresQuery(unsafeSQL: "ROLLBACK"), logger: pgbrainQuietLogger)
                        throw error
                    }
                }
            }
        }

        return Stats(rowsCopied: rowCount.value, elapsed: Date().timeIntervalSince(started),
                     warnings: warnings, sequencesAdvanced: advanced)
    }

    // MARK: - Auto-create type mapping

    struct SourceColumnInfo: Sendable, Equatable {
        let targetName: String
        let type: String            // format_type() on the source
        let typtype: String         // b base, e enum, d domain, c composite, r range, m multirange
        let domainBase: String?
        let isArray: Bool
        let identityOrSerial: Bool
        let notNull: Bool
    }

    private static func sourceColumnInfo(_ c: PostgresConnection, plan: Plan) async throws -> [SourceColumnInfo] {
        let schema = plan.source.schema
        let table = plan.source.name
        let qualified = SQLIdent.qualified(schema: schema, name: table)
        let sql: PostgresQuery = """
        SELECT a.attname,
               format_type(a.atttypid, a.atttypmod),
               t.typtype::text,
               CASE WHEN t.typtype = 'd' THEN format_type(t.typbasetype, t.typtypmod) END,
               t.typcategory = 'A',
               (a.attidentity <> '' OR pg_get_serial_sequence(\(qualified), a.attname) IS NOT NULL),
               a.attnotnull
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_type t ON t.oid = a.atttypid
        WHERE n.nspname = \(schema) AND c.relname = \(table) AND a.attnum > 0 AND NOT a.attisdropped
        """
        var byName: [String: SourceColumnInfo] = [:]
        let rows = try await c.query(sql, logger: pgbrainQuietLogger)
        for try await (name, type, typtype, base, isArray, ident, notNull)
            in rows.decode((String, String, String, String?, Bool, Bool, Bool).self) {
            byName[name] = SourceColumnInfo(targetName: name, type: type, typtype: typtype, domainBase: base,
                                            isArray: isArray, identityOrSerial: ident, notNull: notNull)
        }
        return plan.mappings.map { m in
            guard let info = byName[m.sourceColumn.name] else {
                return SourceColumnInfo(targetName: m.targetColumnName, type: m.sourceColumn.typeName, typtype: "b",
                                        domainBase: nil, isArray: false, identityOrSerial: false, notNull: false)
            }
            return SourceColumnInfo(targetName: m.targetColumnName, type: info.type, typtype: info.typtype,
                                    domainBase: info.domainBase, isArray: info.isArray,
                                    identityOrSerial: info.identityOrSerial, notNull: info.notNull)
        }
    }

    /// Keep the source type when the target knows it (built-ins, extension
    /// types installed there, same-named enums/domains); otherwise fall back
    /// to a domain's base type or to `text` / `text[]`, with a warning.
    private static func resolveTargetColumns(_ c: PostgresConnection, _ info: [SourceColumnInfo]) async throws
        -> ([ColumnSpec], [String]) {
        var specs: [ColumnSpec] = []
        var warnings: [String] = []
        for col in info {
            let decision = try await chooseTargetType(for: col) { candidate in
                try await scalarBool(c, "SELECT to_regtype(\(candidate)) IS NOT NULL")
            }
            if let w = decision.warning { warnings.append(w) }
            let intType = ["smallint", "integer", "bigint"].contains(decision.type)
            specs.append(ColumnSpec(name: col.targetName, type: decision.type,
                                    identity: col.identityOrSerial && intType, notNull: col.notNull))
        }
        return (specs, warnings)
    }

    /// Pure type-mapping decision; `exists` asks the target whether a type name resolves.
    static func chooseTargetType(for col: SourceColumnInfo,
                                 exists: (String) async throws -> Bool) async throws -> (type: String, warning: String?) {
        if try await exists(col.type) { return (col.type, nil) }
        if col.typtype == "d", let base = col.domainBase, try await exists(base) {
            return (base, "\(col.targetName): domain \(col.type) doesn't exist on the target — created as its base type \(base).")
        }
        let fallback = col.isArray ? "text[]" : "text"
        let what = col.typtype == "e" ? "enum" : (col.typtype == "d" ? "domain" : "type")
        return (fallback, "\(col.targetName): \(what) \(col.type) doesn't exist on the target — created as \(fallback).")
    }

    private static func autoCreatePrimaryKey(_ plan: Plan) -> [String] {
        let pk = plan.source.primaryKey
        guard !pk.isEmpty else { return [] }
        var names: [String] = []
        for key in pk {
            guard let m = plan.mappings.first(where: { $0.sourceColumn.name == key }) else { return [] }
            names.append(m.targetColumnName)
        }
        return names
    }

    // MARK: - Post-copy fixups

    /// After explicit values land in serial/identity columns, move each owned
    /// sequence past the copied maximum so the next INSERT doesn't collide.
    /// Only ever raises a sequence.
    private static func advanceSequences(_ c: PostgresConnection, qualified: String, columns: [String]) async throws -> Int {
        var sequences: [(column: String, sequence: String)] = []
        for column in columns {
            let rows = try await c.query("SELECT pg_get_serial_sequence(\(qualified), \(column))", logger: pgbrainQuietLogger)
            for try await seq in rows.decode(String?.self) {
                if let seq { sequences.append((column, seq)) }
            }
        }
        var advanced = 0
        for (column, seq) in sequences {
            let sql = PostgresQuery(unsafeSQL: """
            SELECT setval($1::regclass, x.m, true) FROM (SELECT max(\(SQLIdent.quote(column)))::bigint AS m FROM \(qualified)) x
            WHERE x.m IS NOT NULL AND x.m > COALESCE(pg_sequence_last_value($1::regclass), 0)
            """, binds: try binds(seq))
            let rows = try await c.query(sql, logger: pgbrainQuietLogger)
            for try await _ in rows { advanced += 1 }
        }
        return advanced
    }

    private static func hasAlwaysIdentity(_ c: PostgresConnection, qualified: String, columns: [String]) async throws -> Bool {
        try await scalarBool(c, """
        SELECT EXISTS (SELECT 1 FROM pg_attribute
                       WHERE attrelid = \(qualified)::regclass AND attidentity = 'a' AND attname = ANY(\(columns)))
        """)
    }

    private static func binds(_ values: String...) throws -> PostgresBindings {
        var b = PostgresBindings()
        for v in values { try b.append(v, context: .default) }
        return b
    }

    private static func scalarBool(_ c: PostgresConnection, _ q: PostgresQuery) async throws -> Bool {
        let rows = try await c.query(q, logger: pgbrainQuietLogger)
        for try await v in rows.decode(Bool.self) { return v }
        return false
    }

    private static func scalarInt(_ c: PostgresConnection, _ q: PostgresQuery) async throws -> Int {
        let rows = try await c.query(q, logger: pgbrainQuietLogger)
        for try await v in rows.decode(Int.self) { return v }
        return 0
    }

    // MARK: - Transient target client

    private static func withTargetClient<T: Sendable>(
        _ endpoint: TargetEndpoint,
        _ body: (PostgresClient) async throws -> T
    ) async throws -> T {
        switch endpoint {
        case .existing(let client):
            return try await body(client)
        case .transient(let connection, let password):
            var host = connection.host
            var port = connection.port
            var startedTunnel = false
            if connection.sshEnabled {
                let alreadyUp = await MainActor.run {
                    SSHTunnelManager.shared.tunnels[connection.id]?.process.isRunning ?? false
                }
                port = try await SSHTunnelManager.shared.startTunnel(for: connection)
                host = "127.0.0.1"
                startedTunnel = !alreadyUp
            }
            defer {
                if startedTunnel {
                    let id = connection.id
                    Task { @MainActor in SSHTunnelManager.shared.stopTunnel(for: id) }
                }
            }
            let config = PostgresClient.Configuration(
                host: host,
                port: port,
                username: connection.username,
                password: password.isEmpty ? nil : password,
                database: connection.database.isEmpty ? nil : connection.database,
                tls: try tlsConfig(for: connection.sslMode)
            )
            let client = PostgresClient(configuration: config)
            // Detached task drives the client's I/O loop. Cancelling on exit
            // brings down the pool's connections so we don't leak FDs.
            let runTask = Task.detached(priority: .userInitiated) {
                await client.run()
            }
            defer { runTask.cancel() }
            return try await body(client)
        }
    }

    /// Must stay identical to `ConnectionService.tls(for:)` (private there):
    /// libpq semantics — prefer/require don't verify the certificate,
    /// verify-ca checks the chain only, verify-full also the hostname.
    static func tlsConfig(for mode: Connection.SSLMode) throws -> PostgresClient.Configuration.TLS {
        guard let policy = tlsPolicy(for: mode) else { return .disable }
        var config = TLSConfiguration.makeClientConfiguration()
        config.certificateVerification = policy.verification
        return policy.required ? .require(config) : .prefer(config)
    }

    /// `nil` = TLS off.
    static func tlsPolicy(for mode: Connection.SSLMode) -> (required: Bool, verification: CertificateVerification)? {
        switch mode {
        case .disable: nil
        case .allow, .prefer: (false, .none)
        case .require: (true, .none)
        case .verifyCA: (true, .noHostnameVerification)
        case .verifyFull: (true, .fullVerification)
        }
    }
}

/// Sendable mutable counter (the copy closure runs in a non-main context).
private final class RowCountBox: @unchecked Sendable {
    private var _value: Int = 0
    private let lock = NSLock()
    var value: Int {
        lock.lock(); defer { lock.unlock() }
        return _value
    }
    func add(_ n: Int) {
        lock.lock()
        _value += n
        lock.unlock()
    }
}
