import Foundation
import PostgresNIO

/// One sequence and its current state. `pg_sequences` is a system view
/// (≥ PG 10) that gives us everything we need without per-sequence
/// `currval` calls — and reads `last_value` without bumping it.
struct SequenceInfo: Identifiable, Sendable {
    let id: String          // schema.name
    let schema: String
    let name: String
    let dataType: String
    let startValue: Int64
    let minValue: Int64
    let maxValue: Int64
    let increment: Int64
    let cycle: Bool
    let cacheSize: Int64
    let lastValue: Int64?   // nil when the sequence has never been read
    /// Identity-column owner, if this sequence backs one. Empty string
    /// when standalone.
    let ownedBy: String
}

@MainActor
enum SequenceFetcher {
    static func fetchAll(client: PostgresClient) async throws -> [SequenceInfo] {
        // pg_sequences exposes everything except the owning column —
        // we LEFT JOIN pg_depend → pg_attribute for that so a sequence
        // generated by `GENERATED AS IDENTITY` shows its owner.
        let sql: PostgresQuery = """
        SELECT s.schemaname,
               s.sequencename,
               s.data_type::text,
               s.start_value,
               s.min_value,
               s.max_value,
               s.increment_by,
               s.cycle,
               s.cache_size,
               s.last_value,
               coalesce(
                 (SELECT n2.nspname || '.' || c2.relname || '.' || a.attname
                  FROM pg_depend d
                  JOIN pg_class c2 ON c2.oid = d.refobjid
                  JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
                  JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
                  WHERE d.classid = 'pg_class'::regclass
                    AND d.objid = (s.schemaname || '.' || s.sequencename)::regclass
                    AND d.refobjsubid > 0
                  LIMIT 1),
                 '')::text
        FROM pg_sequences s
        WHERE s.schemaname NOT IN ('pg_catalog','information_schema')
        ORDER BY s.schemaname, s.sequencename
        """
        let rows = try await client.query(sql)
        var out: [SequenceInfo] = []
        for try await (schema, name, type, start, mn, mx, inc, cycle, cache, last, owner)
            in rows.decode((String, String, String, Int64, Int64, Int64, Int64, Bool, Int64, Int64?, String).self) {
            out.append(SequenceInfo(
                id: "\(schema).\(name)",
                schema: schema, name: name,
                dataType: type,
                startValue: start, minValue: mn, maxValue: mx,
                increment: inc, cycle: cycle, cacheSize: cache,
                lastValue: last, ownedBy: owner
            ))
        }
        return out
    }
}
